### ISSUE TITLE
:composeApp:iosArm64Main: Could not find org.jetbrains.kotlinx.multiplatform-library-template:alert-kmp-iosarm64:0.0.1.

### ISSUE THREAD

**Issue by AlaghbariKamel** [KhubaibKhan4/Alert-KMP#1]
:composeApp:iosArm64Main: Could not find org.jetbrains.kotlinx.multiplatform-library-template:alert-kmp-iosarm64:0.0.1.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/multiplatform-library-template/alert-kmp-iosarm64/0.0.1/alert-kmp-iosarm64-0.0.1.pom
  - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/multiplatform-library-template/alert-kmp-iosarm64/0.0.1/alert-kmp-iosarm64-0.0.1.pom
Required by:
    project :composeApp > io.github.khubaibkhan4:alert-kmp:0.0.7

**Comment by KhubaibKhan4** [comment]
Thank you for creating an issue. This issue is due to native functionalities. But you will still can use the alert KMP library without any bugs. It'll just display this error while building the project. This issue will be resolved in the upcoming updates. Thank you again and if you have any features suggestions, please let me know.

**Comment by shariful6** [comment]
i am also facing the same problem

**Comment by KhubaibKhan4** [comment]
It'll be resolved soon.

**Comment by CharlanSofist** [comment]
I'm having a problem trying to build the iOS app in the project https://github.com/KhubaibKhan4/Flexi-Store-KMP, could you help me how to proceed?

`* What went wrong:
Configuration cache state could not be cached: field `libraries` of task `:composeApp:compileKotlinIosSimulatorArm64` of type `org.jetbrains.kotlin.gradle.tasks.KotlinNativeCompile`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Could not resolve all files for configuration ':composeApp:iosSimulatorArm64CompileKlibraries'.
   > Could not find org.jetbrains.kotlinx.multiplatform-library-template:alert-kmp-iossimulatorarm64:0.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/multiplatform-library-template/alert-kmp-iossimulatorarm64/0.0.1/alert-kmp-iossimulatorarm64-0.0.1.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/multiplatform-library-template/alert-kmp-iossimulatorarm64/0.0.1/alert-kmp-iossimulatorarm64-0.0.1.pom
     Required by:
         project :composeApp > io.github.khubaibkhan4:alert-kmp:0.0.7
`

**Comment by 658jjh** [comment]
Still get the error with the latest version

**Comment by KhubaibKhan4** [comment]
Hi @658jjh @shariful6 @AlaghbariKamel @CharlanSofist Sorry for the late response. This issue has been fixed in the latest version `1.0.4`. If you have any features recommendations, please let me know.
